CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"telegram_id" bigint NOT NULL,
	"first_name" varchar NOT NULL,
	"last_name" varchar,
	"username" varchar
);
--> statement-breakpoint
CREATE INDEX "telegram_id_idx" ON "users" USING btree ("telegram_id");